### ISSUE TITLE
p100 error: Local hash does not match server hash

### ISSUE THREAD

**Issue by huyhoang8398** [mihai-dinculescu/tapo#138]
I have this error when trying to use with p100

```
Traceback (most recent call last):
  File "/home/kn/dev/tapo/tapo_p100.py", line 33, in <module>
    asyncio.run(main())
  File "/home/kn/.pyenv/versions/3.10.4/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/kn/.pyenv/versions/3.10.4/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/kn/dev/tapo/tapo_p100.py", line 15, in main
    device = await client.p100(ip_address)
Exception: Other(Local hash does not match server hash)
```

**Comment by kolerak** [comment]
is it posibble that you are entering creditantials incorrectly?

**Comment by huyhoang8398** [comment]
thanks, i forgot to close the issue, i entered wrong credentials

**Comment by mihai-dinculescu** [comment]
I'm reopening this because the error message is not very helpful and it could use a rework.
