### ISSUE TITLE
Failed to install and use API

### ISSUE THREAD

**Issue by pho2Github** [mihai-dinculescu/tapo#149]
Hi Mihai,

I tried to use the API but have two problems.
1. Using Python 3.7 with spyder on my windows PC I received this error message:
```
Traceback (most recent call last):

  File "N:\10_Gemeinsam\Haus\Heizung\Vermessung\Datalogs\TPLink_P115_Auslesen_v2.py", line 32, in <module>
    asyncio.run(main())

  File "C:\ProgramData\Anaconda3\lib\asyncio\runners.py", line 34, in run
    "asyncio.run() cannot be called from a running event loop")

RuntimeError: asyncio.run() cannot be called from a running event loop
```
2. Triying to install the API on my raspberry pi this error
```
pi@raspberrypi:~/Documents $ pip install tapo
Collecting tapo
  Downloading https://files.pythonhosted.org/packages/4a/20/914242caec6a15aae886f5eca36fce0d637b90dc2c2bd97bd5413c546b89/tapo-0.1.0.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 1.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-Bnabi8/tapo/setup.py'

```

Any hint for me?

**Comment by mihai-dinculescu** [comment]
Python 3.8 is the minimum supported version. Can you try with that?

**Comment by pho2Github** [comment]
Thank you, works now with python 3.8.
And sorry, I should have noticed this in the release notes.
