### ISSUE TITLE
Tapo P110 example - Doesn't work

### ISSUE THREAD

**Issue by saepien** [mihai-dinculescu/tapo#330]
I hardcoded login credentials and device IP address on local wifi.
-- 

Local hash does not match server hash
Traceback (most recent call last):
  File "/Users/storm/dev/sandbox/tapo/tap.py", line 61, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/storm/dev/sandbox/tapo/tap.py", line 16, in main
    device = await client.p110(ip_address)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Tapo(InvalidCredentials)

**Comment by mihai-dinculescu** [comment]
Assuming your e-mail is all lowercase, as it should be, and you've got your e-mail and password right, this sounds like the same issue as https://github.com/mihai-dinculescu/tapo/issues/320.
